# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Test against this version of Node.js
os: unstable

cache:
  - 'node_modules -> appveyor.yml,package.json,package-lock.json'
  - 'static/node_modules -> appveyor.yml,static/package.json,static/package-lock.json'

environment:
  matrix:
    - nodejs_version: '8'

matrix:
  fast_finish: true

platform:
  - x32

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -f

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run pretest
  - npm run lint
  - npm run dist:win
  - npm run publish:bos
  - npm run publish:github

# Don't actually build.
build: off
version: "{build}"
shallow_clone: true
clone_depth: 1
